# Generated by Django 5.2.16 on 2026-07-30 05:11

# pyrefly: ignore [missing-import]
import pgvector.django.vector
from django.db import migrations
# pyrefly: ignore [missing-import]
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatuser_userchatsession'),
    ]

    operations = [
        VectorExtension(),
        migrations.RemoveField(
            model_name='pagechunk',
            name='embedding_json',
        ),
        migrations.AddField(
            model_name='pagechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
